# Generated by Django 4.1.3 on 2022-11-05 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='ururlToImagel',
            new_name='urlToImage',
        ),
    ]
